### ISSUE TITLE
Visualization graph is not readable will large graphs

### ISSUE THREAD

**Issue by jstoiko** [aml-org/playground#38]
To address this, I suggest the following:
- remove Document and Dialect from the Visualization demo
- make Graph full screen
- two tabs: Document graph, Dialect Graph to switch between graph
- add a button in each tab saying "Edit this document" that brings back to the validation demo (passing the document content as qs)

**Comment by postatum** [comment]
@jstoiko I think the solution you suggested is overcomplicated. It disables few things:
- Quick edits with immediate feedback visible in graph. Users would have to wait for a few seconds to switch between demos to see results;
- Elements highlight on graph elements click.

I suggest few different solutions (I like 3 and 4 the most):
1. Make editor with tabs and graph take 100% of page width and align them vertically. Editor with tabs will take all width on top of the page and below. See screenshots below.
![1](https://user-images.githubusercontent.com/1999863/60091936-676dc080-974e-11e9-86ba-728ac2ca2eaa.png)
or
![2](https://user-images.githubusercontent.com/1999863/60091903-52912d00-974e-11e9-949e-d7334a860d25.png)

2. Hide editors in some sort of pop-up which will be displayed on some button click.
3. Keep current interface but add "Fullscreen" button next to Zoom-in/out buttons in graph. Clicking on that button will make graph width 100% of the page and hide editor. Clicking on that button again with make graph width 50% of the page and show editor.
4. Same as 3 but graph is 100% of the page width by default and the button is called something like "Show editors".

**Comment by jstoiko** [comment]
I think option 3. is the best. Let's go with this and see how it looks.
