### ISSUE TITLE
Live demo's not working on Edge chromium

### ISSUE THREAD

**Issue by bartroodzant** [aml-org/playground#49]
When I try to open any of the live demo's in Edge Chromium it gives these errors. On Google Chrome they work fine.
![image](https://user-images.githubusercontent.com/15012958/74719305-0ee6b880-5234-11ea-9175-293cef6ad21a.png)

**Comment by postatum** [comment]
Hi @bartroodzant.

Thanks for reporting this issue. I've created a PR that should fix it.
